version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ../Mifaz/Mifaz/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
        
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
        
    environment:
      SA_PASSWORD: "SecureP4ssw0rd?!"
      ACCEPT_EULA: "Y"