version: "3.4"

volumes:
  dbdata:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:5555"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  db:
    container_name: mifaz-db
    image: mariadb:10.3
    volumes:
      - dbdata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"